### PR TITLE
Fixing Breaking changes with removal of word Beta.

### PR DESCRIPTION
**Pull request by EndlesNights**
Sorry I accidently broke support for your module with the last patch, where I changed some name spaces around to remove the word Beta when I changed `dnd4eBeta` to `dnd4e` and `DND4EBETA` to `DND4E`.

Just a pull request that fixes the brake as of the Foundry DnD4e System update v0.4.44.

### CODE REVIEW

**Comment by kyleady** [comment]
Will this change make this module incompatible with older versions of 4e?

If so, is there a way to check the version of the system, and set the names with a variable?

**Comment by EndlesNights** [comment]
Yes this will brake support for older versions.

You can check the system version at `game.system.version` and we can use the helper function `isNewerVersion( currentVersion, VersionToCheck)` to check. I'll set up a new commit in a moment that checks the versions.

**Comment by EndlesNights** [comment]
Give that a quick try, and it should work.

**Comment by kyleady** [comment]
Checked it out, and it looks good. Thank you for fixing this!

**Pull request merged**
